import { formatComment } from '../prompt';

describe('formatComment', () => {
  const HEADER = '🤖 Smart L3 Analysis';
  const FOOTER = 'This analysis was generated by Smart L3. For questions, please consult your L3 team.';
  const REQUIRED_SECTIONS = [
    'Issue Summary',
    'Potential Root Cause(s)',
    'Recommended Solutions',
    'References',
  ];

  it('wraps analysis that already has all section headers', () => {
    const analysis = `## Issue Summary
The service is returning 500 errors.

## Potential Root Cause(s)
A null pointer in the handler.

## Recommended Solutions
Add a null check.

## References
- PR #123`;

    const result = formatComment(analysis);

    expect(result).toContain(HEADER);
    expect(result).toContain(FOOTER);
    for (const section of REQUIRED_SECTIONS) {
      expect(result).toContain(section);
    }
    // Original content should be preserved
    expect(result).toContain('The service is returning 500 errors.');
    expect(result).toContain('PR #123');
  });

  it('adds template sections when analysis is missing headers', () => {
    const analysis = 'Some raw analysis text without any structure.';
    const result = formatComment(analysis);

    expect(result).toContain(HEADER);
    expect(result).toContain(FOOTER);
    for (const section of REQUIRED_SECTIONS) {
      expect(result).toContain(`## ${section}`);
    }
  });

  it('adds template sections when analysis is partially structured', () => {
    const analysis = `## Issue Summary
Something broke.`;

    const result = formatComment(analysis);

    // Missing 3 of 4 sections, so should get the template
    expect(result).toContain(HEADER);
    expect(result).toContain(FOOTER);
    for (const section of REQUIRED_SECTIONS) {
      expect(result).toContain(`## ${section}`);
    }
  });

  it('handles empty analysis output', () => {
    const result = formatComment('');

    expect(result).toContain(HEADER);
    expect(result).toContain(FOOTER);
    for (const section of REQUIRED_SECTIONS) {
      expect(result).toContain(section);
    }
  });
});
